#!/bin/bash
# Variables globales para los scripts DTE Admin
# BIN_DIR y LIB_DIR se encuentran en los scripts de ejecución por necesidades del diseño
#

NOMBRE="DTE Admin"
VERSION=1.0.0
TITULO="$NOMBRE $VERSION"

CONF_DIR=/etc/DTE-Admin
FLAG_CONF_RED_FILE=$CONF_DIR/flag_conf_red
FLAG_CONF_ROUTER_FILE=$CONF_DIR/flag_conf_router

INTERFACES_FILE=/etc/network/interfaces

IPADDR=""
NETMASK=""
IPADDR_ICDR=""
