#!/bin/bash
# Variables globales para los scripts DTE Admin

NOMBRE="DTE Admin"
VERSION=1.0.0
TITULO="$NOMBRE $VERSION"

CONF_DIR=/etc/DTE-Admin
FLAG_FILE=$CONF_DIR/if_conf
BACKUP_DIR=$CONF_DIR/backups

INTERFACES_FILE=/etc/network/interfaces
